# Generated by Django 2.2.1 on 2019-05-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='paid',
        ),
    ]
